version: 1.0.{build}

image:
  - Visual Studio 2022
  - Visual Studio 2019

platform:
  - x64
  - x86

configuration:
  - Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - cmake -B build -DCMAKE_BUILD_TYPE=%CONFIGURATION%
  - cmake --build build --config %CONFIGURATION%

test_script:
  - .\build\%CONFIGURATION%\hello_world.exe
  - echo 1 5 -6 | .\build\%CONFIGURATION%\solver_app.exe
